#!/bin/bash

echo "Socket.IO Command Line Testing Examples"
echo "======================================="
echo ""
echo "Make sure your backend server is running on localhost:3000"
echo "Then run: node test-sockets.js"
echo ""
echo "Example commands to test:"
echo ""
echo "1. Connect as Alice:"
echo "   1 1"
echo ""
echo "2. Update location to Toronto:"
echo "   2 43.6532 -79.3832"
echo ""
echo "3. Refresh user data:"
echo "   3"
echo ""
echo "4. Simulate movement (5 locations over 10 seconds):"
echo "   5"
echo ""
echo "5. Show current status:"
echo "   7"
echo ""
echo "6. Disconnect:"
echo "   6"
echo ""
echo "7. Exit:"
echo "   8"
echo ""
echo "Multi-client testing:"
echo "===================="
echo "1. Open multiple terminal windows"
echo "2. Run 'node test-sockets.js' in each"
echo "3. Connect different users in each window"
echo "4. Test proximity alerts and boops between clients"
echo ""
echo "Example multi-client test:"
echo "Terminal 1: 1 1 (Alice)"
echo "Terminal 2: 1 2 (Bob)"
echo "Terminal 1: 2 43.6532 -79.3832"
echo "Terminal 2: 2 43.6533 -79.3833"
echo "Terminal 1: 4 2 (Alice boops Bob)"
echo ""
echo "This will test:"
echo "- Location updates"
echo "- Proximity alerts (100m radius)"
echo "- Boop functionality"
echo "- Real-time notifications" 